### ISSUE TITLE
FCMServerError: FCM server is temporarily unavailable

### ISSUE THREAD

**Issue by gjain0** [xtrinch/fcm-django#1]
followed the steps, e,g, 

    INSTALLED_APPS = (
            ...
            "fcm_django"
    )
    
    FCM_DJANGO_SETTINGS = {
            "FCM_SERVER_KEY": "[your api key]"
    }

migrated and added one device in the table. 

now I do 

    from fcm_django.models import FCMDevice
    device = FCMDevice.objects.all().first()
    device.send_message("Title", "Message")

this raises an exception saying   **FCMServerError: FCM server is temporarily unavailable**

what could be the reason, am i missing something?

when I debugged it, in pyfcm,  the response from google was 500 (in **pyfcm/baseapi.py**)

**'<HTML>\n<HEAD>\n<TITLE>Internal Server Error</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Internal Server Error</H1>\n<H2>Error 500</H2>\n</BODY>\n</HTML>\n'**

**Comment by xtrinch** [comment]
Ok so if I understand correctly, the error was only temporary and it's working now? @gjain0 Because otherwise I will look into it, perhaps I am sending something that breaks the FCM server

**Comment by gjain0** [comment]
@xtrinch: Yes, it is working now. Thank you :)
