### ISSUE TITLE
Migrations on 0.3.1 are broken

### ISSUE THREAD

**Issue by tpazderka** [xtrinch/fcm-django#106]
The renaming of migrations in `0.3.1` can cause applications that already reference this node to break as the dependency no longer exists.

```
Migration XXX dependencies reference nonexistent parent node ('fcm_django', '0004_auto_20181128_1642')
```

The correct fix should have been to change the dependency but not renaming the file as that serves as a reference for other projects.

**Comment by xtrinch** [comment]
You're correct.. Not sure what to do now, release 0.3.2 with the correct dependency tree and hope that not too many people installed 0.3.0 & 0.3.1?

**Comment by xtrinch** [comment]
I've released 0.3.2 with the correct dependency tree

**Comment by tpazderka** [comment]
This fix works for me, not sure if others might be affected by this.

**Comment by AlexisCaffa** [comment]
works both for me: v0.3.1 and 0.3.2

**Comment by xtrinch** [comment]
Probably depends on django version.
