### ISSUE TITLE
[Question] Will this line cause it to be written twice in the database?

### ISSUE THREAD

**Issue by AlexisCaffa** [xtrinch/fcm-django#107]
If user is authenticated, first, is saved here
https://github.com/xtrinch/fcm-django/blob/3a62f8a821ed7821dfe391794ba5677b24a3a205/fcm_django/api/rest_framework.py#L111 then is resaved in the super class
https://github.com/xtrinch/fcm-django/blob/3a62f8a821ed7821dfe391794ba5677b24a3a205/fcm_django/api/rest_framework.py#L118 

Same in the `perform_update` method https://github.com/xtrinch/fcm-django/blob/3a62f8a821ed7821dfe391794ba5677b24a3a205/fcm_django/api/rest_framework.py#L120

This could probably be better implemented.

**Comment by xtrinch** [comment]
Always accepting pull requests on the matter, you may have a point there

**Comment by AlexisCaffa** [comment]
Indeed, check PR https://github.com/xtrinch/fcm-django/pull/108
