### ISSUE TITLE
push message with using python 6 plus version

### ISSUE THREAD

**Issue by AliAxghar** [xtrinch/fcm-django#109]
I am doing my first steps in django Android interaction to push notification to android from django.
from docs i'm bit confused about the code in viewset, is given code is for viewsets or not ? also about the python version compatibility with fcm django.

from fcm_django.models import FCMDevice

device = FCMDevice.objects.all().first()

device.send_message("Title", "Message")
device.send_message(data={"test": "test"})
device.send_message(title="Title", body="Message", icon=..., data={"test": "test"})

**Comment by AlexisCaffa** [comment]
eh??

**Comment by xtrinch** [comment]
As for python version compatibility, it's compatible with all versions.
The code you pasted can be used outside viewsets without a problem.

Closing as this is a non-issue.
