### ISSUE TITLE
estimated date for next release? [Urgent]

### ISSUE THREAD

**Issue by renato-bvdash** [xtrinch/fcm-django#112]
Currently I am getting this error
```python
ImportError: cannot import name 'python_2_unicode_compatible'
```
and I can see it was fixed but not released yet.
When is the next release getting made?

**Comment by napsterv** [comment]
Hi,
You can remove these 2 lines - Line No.4 and Line no. 10 in fcm-django/models.py and go ahead with the migration. It should start working.

**Comment by xtrinch** [comment]
I'll try to roll it out later this day

**Comment by napsterv** [comment]
> I'll try to roll it out later this day

Thanks, would be looking forward to it.

**Comment by xtrinch** [comment]
0.3.3. rolled out
