### ISSUE TITLE
Can we please have a release?

### ISSUE THREAD

**Issue by napsterv** [xtrinch/fcm-django#113]
I'm working on a live project and this error pops up-
`ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/home/neeraj/PycharmProjects/i100_days/venv/lib/python3.7/site-packages/django/utils/encoding.py)
`

I can already see it in the commits, it's been fixed - #111 
Can we please have a release soon?

**Comment by xtrinch** [comment]
0.3.3. rolled out
