### ISSUE TITLE
commit=False is not allowed in serialzier save method

### ISSUE THREAD

**Issue by dikamilo** [xtrinch/fcm-django#114]
`DeviceViewSetMixin` is broken in 0.3.3 version of fcm-django since drf serializer does not allow `commit=False` on save method.

https://github.com/xtrinch/fcm-django/blob/master/fcm_django/api/rest_framework.py#L111

https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L178

**Comment by xtrinch** [comment]
Might be easy to just revert https://github.com/xtrinch/fcm-django/pull/108

**Comment by AlexisCaffa** [comment]
Then, how to solve this https://github.com/xtrinch/fcm-django/issues/107 ?

**Comment by anindyamanna** [comment]
I had to revert to 0.3.2
