### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by SerhiyRomanov** [xtrinch/fcm-django#119]
What do you think about dropping support of Python 2 in one of future major releases?

Also it would be nice add tests only for Python3 ( in scope of #79) afterwards. It seems like clean and reliable way to go through.

// I actively use this package, so I can help with implementation.

**Comment by xtrinch** [comment]
I'm not entirely sure about dropping python2 support, maybe the users have more input on this. 
As for the tests, python3 tests is better than no tests, would very much appreciate the help 👍

**Comment by xblitz** [comment]
:+1:  for dropping Python 2, as most modules are also doing it, django also has dropped support. should simplify the codebase

**Comment by xtrinch** [comment]
Convincing enough, sounds good to me
