### ISSUE TITLE
User ForeignKeyField in Device makes this difficult to work with in a microservices environment

### ISSUE THREAD

**Issue by martyzz1** [xtrinch/fcm-django#128]
I've been racking my brains as to how I might make use of your project. I have a microservices environment using SimpleJWT, but with the TokenUser not being a Database Model. There is no user model to have a foreignkey relationship with...

I was thinking of overriding the FCMDevice model, but that would ultimitely still cause some issues...

The best I can think of is to simply import all the various pieces into my own app and try to customise as little as possible... I was wondering if this is a feature thats worth trying to bake into fcm-django... it kinda feels like the FCMDevice class could be overridable and confgured in Settings. like AUTH_USER_MODEL is..

**Comment by xtrinch** [comment]
There were some people already trying to modify the FCMDevice model:
https://github.com/xtrinch/fcm-django/issues/57
I think you should be fine with using the abstract class that was merged in the PR they provided
