### ISSUE TITLE
How Can I stet up this properly in my django project.

### ISSUE THREAD

**Issue by saileshkush95** [xtrinch/fcm-django#129]
I new to push notification, so I'm sorry for this stupid questions and also I'm unclear about some the terminology used in this package. Here I've some question.
-Is the server key and fcm api key is same?
-do i need to add some extrnal js script ko make this package work properly. if can you please share some guide or pdf or some link which help me to integrate this.
-Do i need to add FCM Device manually? Please make me clear about fcm device.
-After setup this project, i didn't get any notification to enable or disable push notifications.
Here is my setup

settings.py
```
INSTALLED_APPS = [
.......
    "fcm_django",
]
FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAA......:................................................MGC22WxjWHHcKOo"
}

Note: FCM_SERVER_KEY is server key instead of web api key
```
If i need to add FCM Device how can i add FCM Devices properly, because i didn't know, from where and how to garb all the value for model FCM Device model fields.

**Comment by xtrinch** [comment]
-Is the server key and fcm api key is same?
No, one is for server, one is for client (your most often javascript code).

-do i need to add some extrnal js script ko make this package work properly. if can you please share some guide or pdf or some link which help me to integrate this.
For the client, yes. Check out my example client javascript project @ fcm-django-web-demo. There's a link in the description.

-Do i need to add FCM Device manually? Please make me clear about fcm device.
Yes, you need to add it manually, as you would any other django model. Play around with the example and it should be clear to you.

-After setup this project, i didn't get any notification to enable or disable push notifications.
If all you have is django as your backend, there will not be any such notifications. That is for the client. Once again I encourage you to check out the example.

**Comment by xtrinch** [comment]
Feel free to re-open if any more issues pop up!
