### ISSUE TITLE
Send rich notifications in iOS

### ISSUE THREAD

**Issue by monicaphalswal** [xtrinch/fcm-django#13]
I'm not able to send `"mutable_content": True`  in extra kwargs as an additional keyword argument (which is required to send rich notifications to iOS). I am getting `notify_single_device() got an unexpected keyword argument 'mutable_content'` error. I looked in PyFCM documentation, it supports this field in additional arguments. Please help.

**Comment by monicaphalswal** [comment]
Please reply. Is this an issue with fcm-django because I was able to send this key with pyFCM?

**Comment by xtrinch** [comment]
How are you passing kwargs and which version of pyfcm and fcm-django library are you using?

**Comment by pramodmauryaiiita** [comment]
[c9e4bad](https://github.com/olucurious/PyFCM/commit/c9e4bad937d44a903f2b0f1af8aa6fcf2d1c7d44)
@monicaphalswal check this commit, I think you're using older version of PyFCM

**Comment by monicaphalswal** [comment]
The version info is as below for the two packages:
Name: pyfcm
Version: 1.2.9

Name: fcm-django
Version: 0.2.7

```
kwargs = {
        'content_available': True,
        'time_to_live': 30,
        'mutable_content': True
    }

devices.send_message(
            title="Name", 
            icon="appicon",
            data={
                "notification type" : 2,
            },
            **kwargs
        )
```

I am getting error: `TypeError: notify_single_device() got an unexpected keyword argument 'mutable_content'`

**Comment by xtrinch** [comment]
On a second look, there actually is no mutable content as a keyword argument in that function, so you should be passing it in an 'extra_kwargs' dict in 'kwargs'. 

For example: 

`kwargs = { extra_kwargs = { mutable_content: True } }`

Let me know if that works for you.
