### ISSUE TITLE
please add a feature to disallow registring_id with out a user.

### ISSUE THREAD

**Issue by harem234** [xtrinch/fcm-django#130]

**Comment by xtrinch** [comment]
I'm afraid you'll have to elaborate a bit more on your feature request, I don't understand.

**Comment by harem234** [comment]
Hi, sorry for talking so short.
in the FCMDeviceAuthorizedViewSet, even if the user in Anonymous the registration id will be saved with user == null,
I hope to override that to be disallowed, or let me know witch part of code is safe to override.

thanks a lot for your time.

**Comment by xtrinch** [comment]
The authorized view set should not allow you to save the device without an user. If that is the case, then it's a bug.

**Comment by harem234** [comment]
the FCMDeviceAuthorizedViewSet, uses perform_create method from the Class DeviceViewSetMixin
      
    def perform_create(self, serializer):
        if is_user_authenticated(self.request.user):
            if (SETTINGS["ONE_DEVICE_PER_USER"] and
                    self.request.data.get('active', True)):
                FCMDevice.objects.filter(user=self.request.user).update(
                    active=False)
            return serializer.save(user=self.request.user)
        return serializer.save()

as we see, even if the user is not present, it will be save instead of raising permission error.

**Comment by harem234** [comment]
Sorry look like it was my mistake at some point.
it is working just fine.
