### ISSUE TITLE
Questions about send bulk messages and timeout

### ISSUE THREAD

**Issue by yurabysaha** [xtrinch/fcm-django#139]
I can see that `notify_multiple_devices` in` pyfcm/fcm` has `timeout` for send request and` timeout is 5.`

I have near 10k registration ids and when I send push to all I can see warning in logs

`Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='fcm.googleapis.com', port=443): Read timed out. (read timeout=5)")': /fcm/send`

So, my questions:
Why this timeout is 5?
Why this error appears ?
Did all my Users receive push notifications?
As we can see retries here, did it mean that some of my users can be spammed by few same pushes? 

Thank in advance!

**Comment by xtrinch** [comment]
I don't think any of your users got the push notifications, it looks like it couldn't reach the FCM servers. Have you tried adding a device you own, and seeing if it gets the push notification?

**Comment by xtrinch** [comment]
I see that there is a new version of pyFCM where the timeout is increased. Bumping its version should help you.

**Comment by xtrinch** [comment]
Bump the version of this package to 0.3.6
