### ISSUE TITLE
After downloading, less a migrate file 0003_auto_20170313_1314.py

### ISSUE THREAD

**Issue by eileen-chen** [xtrinch/fcm-django#14]
pip install fem-django

fem-django package migrate folder not include 0003_auto_20170313_1314.py

my error message
raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration citizens.0011_auto_20170403_1330 dependencies reference nonexistent parent node ('fcm_django', '0003_auto_20170403_1330')

**Comment by xtrinch** [comment]
Try version 0.2.7 that I just released

**Comment by eileen-chen** [comment]
ok, thanks
