### ISSUE TITLE
__init__() got an unexpected keyword argument 'json_encoder' in python 3.6.9

### ISSUE THREAD

**Issue by ishmam-hossain** [xtrinch/fcm-django#141]
When I'm trying to send_message, I'm getting this error in my server which uses python version 3.6.9. But it works just fine locally with python version 3.8.5.

`TypeError /admin/fcm_django/fcmdevice/
__init__() got an unexpected keyword argument 'json_encoder'`

Sentry log:
`        InternalPackageError: JSON parsing error, mostly from changes in the
            response of FCM, create a new github issue to resolve it.
    """`
```
    if api_key is None:
        api_key = SETTINGS.get("FCM_SERVER_KEY")
    push_service = FCMNotification(api_key=api_key, json_encoder=json_encoder) ******
    result = push_service.notify_single_device(
        registration_id=registration_id,
        message_title=title,
        message_body=body,
        message_icon=icon,```

issue is in the starred line on code. Can anyone help? Thanx in advance!

**Comment by xtrinch** [comment]
This is an error thrown in pyFcm, are you sure you are running the same versions locally and on the server?
Otherwise it's an issue that has to be opened with pyFcm, because it's their constructor that throws this error

**Comment by ishmam-hossain** [comment]
Yes! PyFcm version is 1.4.7 in both server and local machine. And the fcm-django version is 0.3.4. 
Thank you!
