### ISSUE TITLE
pyfcm version

### ISSUE THREAD

**Issue by xblitz** [xtrinch/fcm-django#142]
I see that in this commit https://github.com/xtrinch/fcm-django/commit/bea0a6ded740df9472d036125d012dfef16480c4 you have changed the requirements for pyfcm to 1.4.8 , but this version does not exist, and the pyfcm version in the setup.py is still at 1.4.7 
Was this intentional?

**Comment by xtrinch** [comment]
Uf, no. Fixed in release 0.3.7
