### ISSUE TITLE
Info: support for FCM HTTP v1 API

### ISSUE THREAD

**Issue by ipiga94** [xtrinch/fcm-django#144]
Hello,
thank you for your work! I have a question: does the current release use the FCM HTTP v1 API?

**Comment by affan10** [comment]
Would also like to know this. And if it does, which was the last version that used the Legacy API?

**Comment by xtrinch** [comment]
This library is just a wrapper around PyFcm (https://github.com/olucurious/PyFCM), which is the one that deals with FCM directly, so you should be able to find more info there. I am keeping it always up to date, so the last version of it is always included.

**Comment by daadu** [comment]
pyfcm uses Legacy APIs, and looks like there is no plan to move to HTTPv1APIs [https://github.com/olucurious/PyFCM/issues/165]

**Comment by daadu** [comment]
@xtrinch I like the django integration part of this package (DRF views, Device models, and query_manager methods "send_message"), it would be great if we plan to move to firebase admin sdk [https://github.com/firebase/firebase-admin-python], which is maintained officially. I am ok, if this is not backward compatible by properly bumping the version, where 0.X.X uses `pyfcm` "backend" while `1.X.X` uses `firebase_admin`.

**Comment by daadu** [comment]
I am sure this won't be trival. But I would like to contribute if there is a plan.

**Comment by daadu** [comment]
Now that I think about it, I would like the `FCMDevice` to be backward compatible (with proper migrations), so that someone can easily migrate (data-wise) from 0.X.X to 1.X.X

**Comment by xtrinch** [comment]
Yeah, there seemed to have been a plan to do the migration over at pyFcm a couple of years ago but there is no movement on that front.

I don't think there would need to be drastic changes to the user-facing interfaces, and see FCMDevice to be potentially backwards compatible without any data migration. If not, proper migrations can be supplied and it shouldn't be a problem.

I'd be happy to do a collaboration on this, if you'd like to get us started.

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch I'll get started on the migration. Seems like this package is more maintained than the one at Jazzband, so happy to help here and get #126 resolved at the same time. I'll probably fix #126 first so that both v0 and v1 have the update.

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch I'm confused. What's the difference between this package and jazzband/django-push-notifications ? Besides the models, most of the code is the exact same?

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch @ipiga94 @daadu @affan10 if any of you would like to test #160 to fix this, please do! I didn't test the code at all since I got lazy and didn't use the demo.

**Comment by xtrinch** [comment]
@Andrew-Chen-Wang this package was created out of django-push-notifications' code base back when they did not support FCM yet and I guess some people found it useful and used it :-)
