### ISSUE TITLE
Sending silent notifications

### ISSUE THREAD

**Issue by affan10** [xtrinch/fcm-django#145]
We have a MobileApp with a Django backend. For our simple use-case, to detect deleted apps, we're sending silent notifications like this:

```
devices = FCMDevice.objects.filter(active=True)
for device in devices:
       result = device.send_message(title=None, body=None, data=None)
       # Inspecting the result to check if errors were returned such as NotRegistered, InvalidRegistration 
       # and setting this device to active=False in our database
```

This used to work pretty well until about 2-3 weeks ago. Previously, nothing used to get displayed on a user's screen. But now, we've observed that in some instances, an empty notification without any text whatsoever does pops-up.

@xtrinch Isn't this way sufficient to send silent notifications via fcm_django? What has changed that could be a possible reason for this to happen?

Versions:
fcm_django==0.3.4
pyfcm==1.4.7
django==3.1.3

**Comment by prafulbagai** [comment]
Were you able to find the solution for this?

**Comment by affan10** [comment]
Nope.

**Comment by SilverStrings024** [comment]
@affan10 
@xtrinch 
It looks like it could possibly be done with the extra kwargs. If you send {"content-available": True} it's supposed to send a silent notification but delivery isn't gaurenteed based on a few factors.

So try passing {"content-available": True}  to the extra_kwargs and see if that works

Source: https://stackoverflow.com/questions/37570200/firebase-silent-apns-notification

**Comment by affan10** [comment]
Thank you @SilverStrings024. For now we've deprioritized this issue as it wasn't critical. I'll close this ticket until I test out your suggestion :)

**Comment by SilverStrings024** [comment]
> Thank you @SilverStrings024. For now we've deprioritized this issue as it wasn't critical. I'll close this issue until I test out your suggestion :)
> 
> Just for clarification, you mean doing the following:
> extra_kwargs = {"content_available": True}
> device.send_message(title=None, data=None, body=None, **extra_kwargs)  # note the ** or just simply extra_kwargs
> 
> NOTE: I'm using fcm-django 0.3.7

No problem, please do let me know if it works because silent motifs are extremely useful.
