### ISSUE TITLE
How to handle duplicate registration IDs

### ISSUE THREAD

**Issue by colehorvitz** [xtrinch/fcm-django#147]
Hi, I am curious about this line in the documentation: 

> Will allow duplicate registration_id’s for different users, so you are responsible for cleanup (if that is generally perceived as undesired behaviour or if the package itself should be doing the cleanup, open an issue or email me)

What is the recommended way of handling this cleanup?

**Comment by xtrinch** [comment]
Perhaps on logout, or as a periodic cleanup.

**Comment by xtrinch** [comment]
For DRF, you can now use the `UPDATE_ON_DUPLICATE_REG_ID` setting, in case you don't want duplicate registration ID's and you would rather just update the FCM Device. Feel free to re-open if any questions remain.
