### ISSUE TITLE
Sending topic messages

### ISSUE THREAD

**Issue by mahimatiwary345** [xtrinch/fcm-django#148]
Hi @xtrinch,
I am working on using this library to send messages to all users subscribed to a particular topic. The documentation on the same barely covers anything and I cannot find any solution anywhere else on the internet for the same. 

Is it an active feature in the library? If so, can you provide a proper documentation on how to subscribe users to a topic and send topical notifications?

**Comment by xtrinch** [comment]
You can send topic messages via the `notify_topic_subscribers` function, the subscribe method has not been exposed from the underlying pyFcm yet but you can read all about it here https://github.com/olucurious/pyfcm

**Comment by Andrew-Chen-Wang** [comment]
When we migrate to v1, you can do:

When we finish the migration from v1, you can do:

```python
from firebase_admin.messaging import Message, Notification

queryset.send_message(Message(topic=""))
```
