### ISSUE TITLE
Error in FCMDeviceAuthorizedViewSet

### ISSUE THREAD

**Issue by kitanin90** [xtrinch/fcm-django#151]
![image](https://user-images.githubusercontent.com/32891674/114429575-f58e9180-9bd6-11eb-9379-b772e126e62b.png)

Error, what am I doing wrong? I substituted JWT Token, it doesn't help

python 3.8.5
django3.1

**Comment by kentuck13** [comment]
FCMDeviceAuthorizedViewSet - require authentication

```
class AuthorizedMixin(object):
    permission_classes = (permissions.IsAuthenticated, IsOwner)

 ....
class FCMDeviceAuthorizedViewSet(AuthorizedMixin, FCMDeviceViewSet):
    pass

```

**Comment by xtrinch** [comment]
What @kentuck13 said. You need to provide the correct token in the headers.
