### ISSUE TITLE
How to set the priority of the notification?

### ISSUE THREAD

**Issue by prafulbagai** [xtrinch/fcm-django#156]

**Comment by xtrinch** [comment]
Use the 'low_priority' prop that you can pass on sending.

**Comment by hosseinmp76** [comment]
@xtrinch is 'low_priority' still available? if so can you add a sample in readme or docs? I can't find how to set priority in notif.

**Comment by xtrinch** [comment]
@hosseinmp76 This basically boils down to how you construct the message, which is best followed by the official firebase-admin docs. An example would be:

```
message = messaging.Message(
    android=messaging.AndroidConfig(
        priority='normal',
        notification=messaging.AndroidNotification(
            title='test',
            body='test123',
        ),
    ),
)
```
