### ISSUE TITLE
"This field must be unique" error when trying to update device owned by multiple users

### ISSUE THREAD

**Issue by FrederikVds** [xtrinch/fcm-django#16]
In my application, I support multiple users using the same device (and thus having the same registration ID). Create and delete queries work fine this way (the registration ID correctly gets set to inactive for all other users when it's created for one user). But when trying to update an existing registration ID, to make it inactive when the user logs out from the device, I get a "This field must be unique" error on the registration_id field.

Expected behaviour: if the update sets the notification device to active, set notification devices with the same registration ID owned by other users to inactive and then do the update. Otherwise, just do the update.

Cause: in api/rest_framework.py, there's logic to handle this for create queries, starting at line 42. The same logic is missing for update queries (starting at line 39).

Workaround: delete and re-create the notification device instead.

**Comment by xtrinch** [comment]
Makes sense. Thank you.

**Comment by Almaral-Engineering** [comment]
How can I delete and re-create the notification device?
