### ISSUE TITLE
TypedDict is for python 3.8+

### ISSUE THREAD

**Issue by MHM5000** [xtrinch/fcm-django#161]
Hi,
We should either remove the use of `TypedDict` in `fcm_django/models.py`, use something else or add `python_requires=">=3.8"` to setup in `setup.py` and update the documentations.

**Comment by MHM5000** [comment]
We could use this solution: https://stackoverflow.com/a/53410614/1260025
It includes adding mypy and mypy_extensions

**Comment by xtrinch** [comment]
TBH in this case it's probably better to use the likes of NamedTuple and avoid extra depencies. And we definitely we should support python < 3.8

**Comment by xtrinch** [comment]
Perhaps something like https://github.com/xtrinch/fcm-django/pull/162

**Comment by MHM5000** [comment]
yes. that would work.

**Comment by xtrinch** [comment]
Merged PR, will release with next version
