### ISSUE TITLE
Getting Error to install 1.0.0 version

### ISSUE THREAD

**Issue by caiquestow** [xtrinch/fcm-django#163]
Hey lads, i am trying test the new fcm-django version but i didn't have success... did it happen the same with someone?
I am using docker with Django==2.2.24 

    ERROR: Command errored out with exit status 1:
     command: /opt/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kpywjdes/fcm-django/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kpywjdes/fcm-django/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-frlc6jzi
         cwd: /tmp/pip-install-kpywjdes/fcm-django/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kpywjdes/fcm-django/setup.py", line 2, in <module>
        import fcm_django
      File "/tmp/pip-install-kpywjdes/fcm-django/fcm_django/__init__.py", line 1, in <module>
        from django import VERSION as DJANGO_VERSION
    ModuleNotFoundError: No module named 'django'
    ----------------------------------------

**Comment by xtrinch** [comment]
I think we should be fine just removing the check for the django version in the `fcm_django/__init__.py`, it would just be an extra variable for the newer versions that doesn't do anything.

@Andrew-Chen-Wang what do you think?

**Comment by Andrew-Chen-Wang** [comment]
That check was added due to Django 3.2 dropping support for `default_app_config`. If we didn't do that `if statement`, everyone's projects' CIs would include a warning.

The fix for us in this case is to create a file called `__version__.py` and place our versions in there instead.

**Comment by Andrew-Chen-Wang** [comment]
Pip installation should now work in #165 . Run `pip install git+git://github.com/Andrew-Chen-Wang/fcm-django.git@versioning` for test

**Comment by xtrinch** [comment]
Not sure that would fix the original poster's issue or create a new one, since he's using django 2.2. I'm thinking maybe he's not using the same virtual env where his django resides

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch no the original issue is raised during a basic pip install due to the current environment perhaps not having django installed already (if Django is already installed, you won't bump into this error).

Django has been using the same variable and syntax for version for its lifetime.

**Comment by Andrew-Chen-Wang** [comment]
Totally valid error for someone using containerization where you need to continuously pip install on docker build.

**Comment by xtrinch** [comment]
Alright, cool. Did a 1.0.1 release, should then fix the original poster's issue
