### ISSUE TITLE
Migrationss Error Specified key was to long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by tracesense** [xtrinch/fcm-django#170]
Hi Error when running migrations; specific key was too long; max key length is 3072 bytes. Any ideas how to fix? mySQL.

**Comment by xtrinch** [comment]
Oh. It will have to be 3072 then.. If anyone's migrations have gone through already, they will sadly have to update their DB manually.

**Comment by xtrinch** [comment]
Oh. I guess it will have to be 1000 then. If it turns out to be too little, we may have to get rid of the index on this column. I'll update the migrations, and if anyone has ran them already, they'll have to manually update their DB value.

**Comment by xtrinch** [comment]
Fixed in 1.0.3

**Comment by tracesense** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
