### ISSUE TITLE
MySQL error the specified key was too long; max key length is 3072.

### ISSUE THREAD

**Issue by farmanalibhatti** [xtrinch/fcm-django#174]
While migrating, this error is thrown. I have tried changing the engine to InnoDB but no luck. Tried changing the collation but didn't solved it. If you can suggest a solution, it will be really helpful. It work fine with postgres but out application db is in mysql.
![image](https://user-images.githubusercontent.com/63158775/129227208-5c498bf9-f6a9-44d0-b43f-f1ad1683032e.png)

**Comment by xtrinch** [comment]
I don't think you're using the latest version.

**Comment by xtrinch** [comment]
Should be fine now with the latest release
