### ISSUE TITLE
pip install fcm-django gives error

### ISSUE THREAD

**Issue by jatindergit** [xtrinch/fcm-django#181]
![Screen Shot 2021-08-31 at 4 37 22 PM](https://user-images.githubusercontent.com/15045055/131492329-3e4af4b5-3263-4680-a40b-5ff30af6363e.png)

**Comment by salberin** [comment]
I could be wrong, but it seems that your development environment is missing some standard development header files. Under Ubuntu, this  would be an install of the build-essential package, but I don't know how this would work under Windows.

**Comment by xtrinch** [comment]
Yeah doesn't look like a fcm-django issue, closing
