### ISSUE TITLE
models.py: Line 269

### ISSUE THREAD

**Issue by aammundi** [xtrinch/fcm-django#183]
I've been scratching my head to try and understand what this line does/means and how it works

models.py: Line: 269
```
...
...
objects: "FCMDeviceQuerySet" = FCMDeviceManager()
```

Shouldn't it just be:
`objects = FCMDeviceManager()`

Could someone please educate me.

**Comment by aammundi** [comment]
finally found it. 
https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526

**Comment by xtrinch** [comment]
Cool glad you figured it out
