### ISSUE TITLE
Exactly one of token, topic or condition must be specified.

### ISSUE THREAD

**Issue by andre19rodrigues** [xtrinch/fcm-django#184]
When sending messages to topics, this exception is raised: "Exactly one of token, topic or condition must be specified."

Exception Location: ...project/venv/lib64/python3.8/site-packages/firebase_admin/_messaging_encoder.py, line 681, in default

```
    def default(self, o): # pylint: disable=method-hidden
        if not isinstance(o, Message):
            return json.JSONEncoder.default(self, o)
        result = {
            'android': MessageEncoder.encode_android(o.android),
            'apns': MessageEncoder.encode_apns(o.apns),
            'condition': _Validators.check_string(
                'Message.condition', o.condition, non_empty=True),
            'data': _Validators.check_string_dict('Message.data', o.data),
            'notification': MessageEncoder.encode_notification(o.notification),
            'token': _Validators.check_string('Message.token', o.token, non_empty=True),
            'topic': _Validators.check_string('Message.topic', o.topic, non_empty=True),
            'webpush': MessageEncoder.encode_webpush(o.webpush),
            'fcm_options': MessageEncoder.encode_fcm_options(o.fcm_options),
        }
        result['topic'] = MessageEncoder.sanitize_topic_name(result.get('topic'))
        result = MessageEncoder.remove_null_values(result)
        target_count = sum([t in result for t in ['token', 'topic', 'condition']])
        if target_count != 1:
            raise ValueError('Exactly one of token, topic or condition must be specified.')
        return result
        
```

My code:
```
message = Message(notification=Notification(title=title, body=body), topic="xyz")
devices = FCMDevice.objects.all()
devices.send_message(message)
```

The problem occurs because both token and topic are present in "result", therefore `target_count` is 2. To overcome this issue, I am discarding the `result['token']` if `result['topic']` exists.

Setting `skip_registration_id_lookup=True` does not solve the problem.

**Comment by Andrew-Chen-Wang** [comment]
Hm, maybe the docs are wrong to say you should send topic messages along with devices that have tokens specified... it might just be better if we implemented a `send_topic_message` and all it does is `messaging.send_message(Message(topic=""))`. where you provide the Message object.

**Comment by keomabrun** [comment]
Hi @Andrew-Chen-Wang, thank you for your feedback.
I am not sure I understand the solution though, is there a way way to send a topic message without having the modify the package source as @andre19rodrigues mentioned ?

**Comment by keomabrun** [comment]
I finally used `messaging.send()` from the `firebase_admin` package directly as you mentioned. Thanks!

**Comment by xtrinch** [comment]
Yeah the docs are definitely misleading on the matter and we should provide a send_topic_message method.

**Comment by xtrinch** [comment]
I've updated the docs for in the mean time with this:
```
    from firebase_admin.messaging import send_message

    messaging.send_message(Message(data={...}, topic="TOPIC NAME")
```
