### ISSUE TITLE
How can we add click_action inside the devices.send_message(Message(notification=Notification(...)))?

### ISSUE THREAD

**Issue by onshadeep** [xtrinch/fcm-django#185]
Here what I had tried to use 
` devices.send_message(Message(notification=Notification(title=self.title, body=self.description, click_action=self.link)))`
but getting error 

`TypeError: __init__() got an unexpected keyword argument 'click_action'`
I am looking to send the notification as click action on android,web,ios

**Comment by Andrew-Chen-Wang** [comment]
That's because the Notification constructor does not have a "click_action". What you want to do is do `Message(data={"click_action": self.link})`

**Comment by onshadeep** [comment]
@Andrew-Chen-Wang Yes, It's working now, Thanks a lot
