### ISSUE TITLE
data_message or data - field in send_message()

### ISSUE THREAD

**Issue by gjain0** [xtrinch/fcm-django#2]
https://github.com/xtrinch/fcm-django
in readme, it is 
`device.send_message(title="Title", body="Message", icon=..., data_message={"test": "test"})`

https://github.com/xtrinch/fcm-django/blob/master/fcm_django/models.py
but when I look at the code, I dont see any **data_message** field instead i see **data**.

Can you please update whichever is wrong?

**Comment by xtrinch** [comment]
Whoops, typo in readme. With "data" it should be working. I will fix readme, let me know if "data" works for you.
