### ISSUE TITLE
How to implement multiple FCK keys

### ISSUE THREAD

**Issue by marloncepeda** [xtrinch/fcm-django#20]
Hello, I have two projects that use FCM, the first one is the store that receives the purchase orders, the second is the buyer who makes the orders, for each I have different projects and different FCK keys, how can I make the server have two Keys and send to my buyer and seller push notifications.

**Comment by xtrinch** [comment]
Is it absolutely necessary to use two different keys?

**Comment by sdbriney** [comment]
My solution to this feature is in this pull request https://github.com/xtrinch/fcm-django/pull/28

**Comment by xtrinch** [comment]
Solution merged, closing issue :)
