### ISSUE TITLE
“python_requires” should be set with “>=3.6”, as fcm-django 1.0.8 is not compatible with all Python versions.

### ISSUE THREAD

**Issue by PyVCEchecker** [xtrinch/fcm-django#200]
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found it is not compatible with **Python<3.6**. My local Python version is 2.7, and I encounter the following error when executing _“pip install fcm-django”_ 

```
Collecting fcm-django
  Downloading https://files.pythonhosted.org/packages/a4/5b/fccc4a6b99851757e0d841a919630899c86369e59dd9bcc198d003509c5a/fcm_django-1.0.8-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement firebase-admin<6,>=5 (from fcm-django) (from versions: 1.0.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.15.1, 2.16.0, 2.17.0, 2.18.0, 3.0.0, 3.1.0, 3.2.0, 3.2.1)
ERROR: No matching distribution found for firebase-admin<6,>=5 (from fcm-django)
```
Dependencies of this distribution are listed as follows:
```bash
"firebase-admin>=5,<6", 
"Django"
```
I found that **firebase-admin>=5,<6** requires **Python>=3.6**, which results in installation failure of fcm-django in Python 2.7.

Way to fix:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires=">=3.6",
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by xtrinch** [comment]
Thank you for reporting this, I've added `python_requires=">=3"` to setup.py
