### ISSUE TITLE
Cover with tests?

### ISSUE THREAD

**Issue by olzhasar** [xtrinch/fcm-django#204]
Hi,

Thank you for your project, it is really handy. However, the fact it doesn't have any tests makes it less attractive to use in production projects. Have you considered covering with tests?

I think it would be nice to test all the functionality and also set up [tox](https://tox.wiki/en/latest/) to ensure everything works with different versions of libraries (Django, DRF, firebase-admin)

Let me know if you need any help with test coverage

**Comment by xtrinch** [comment]
Yeah, it would be really great to have tests. I never find the time to get around to it. I would greatly appreciate any pull requests on the matter!
