### ISSUE TITLE
related_query_name value of Device.user field changed at 1.0.9

### ISSUE THREAD

**Issue by ShudelEV** [xtrinch/fcm-django#205]
related_query_name="fcmdevice" (by default) was before 1.0.9 version and changed to related_query_name="device".
It raises incompatible change by upgrading minor version. 
For instance, using fcm-django=1.0.8 `User.objects.filter(fcmdevice__type="ios")`, Django raises `django.core.exceptions.FieldError: Cannot resolve keyword 'fcmdevice' into field. Choices are:  .., device, device_id, ..` with fcm-django=1.0.9

**Comment by xtrinch** [comment]
Probably not the greatest thing. Changed to fcmdevice in 1.0.10
