### ISSUE TITLE
Only one device by user

### ISSUE THREAD

**Issue by Pablo849** [xtrinch/fcm-django#21]
Hi. By designing my application, each user can only have one active device. What would be the fastest way to implement it?
Thank you.

**Comment by xtrinch** [comment]
Although you haven't mentioned how exactly your application should respond when a user with a registered device tries to register a new one:

When the user wants to register a new device, delete the old device from the same user.

Perhaps register a django pre-save handler and in it delete the old device.

**Comment by BojanKogoj** [comment]
You can also only use the last added device, though this could lead to weird issues

`device = FCMDevice.objects.filter(user=user, active=True).last()`

Or you could do what @xtrinch suggested, except in my example I use post_save

```python
@receiver(post_save, sender=FCMDevice, dispatch_uid="my_unique_identifier")
def clean_old_devices(sender, instance, created, **kwargs):
    FCMDevice.objects.filter(user=user, active=True).exclude(instance).delete()
```

**Comment by xtrinch** [comment]
I think this could probably be added to fcm-django settings and deleted within the package, since there seems to be a need for it.

**Comment by xtrinch** [comment]
I've added additional settings: ONE_DEVICE_PER_USER and DELETE_INACTIVE_DEVICES, with which you should be able to achieve all the above mentioned. Will be releasing a new version soon.

**Comment by Pablo849** [comment]
That's great, thanks for the effort. Thank you all for the contributions as well. Greetings.
