### ISSUE TITLE
No sound for IOS notifications

### ISSUE THREAD

**Issue by avatarKaran** [xtrinch/fcm-django#214]
Sending notifications works , however no sound is played on the device when the notification arrives.

**Comment by avatarKaran** [comment]
any one having this issue?

**Comment by xtrinch** [comment]
Please share your code/configuration of the notification, it's impossible to know more without

**Comment by avatarKaran** [comment]
fcmdevicee = FCMDevice.objects.get(user=usertosendto)
                                   
                    fcmdevicee.send_message(Message(
                        notification=Notification(
                            title=f"{myself.username} sent you a picture ")


                    ))


Thanks for getting back to me. So everything works fine in terms of sending the notification etc. Android there is sound but on IOS the sound doesn't play.

**Comment by avatarKaran** [comment]
> Please share your code/configuration of the notification, it's impossible to know more without

fcmdevicee = FCMDevice.objects.get(user=usertosendto)
                                   
                    fcmdevicee.send_message(Message(
                        notification=Notification(
                            title=f"{myself.username} sent you a picture ")


                    ))


Thanks for getting back to me. So everything works fine in terms of sending the notification etc. Android there is sound but on IOS the sound doesn't play.

**Comment by xtrinch** [comment]
I was unable to find any setting for this in the notification options of firebase-admin. You can only add a custom sound. The handing is therefore as ios handles it by default.
