### ISSUE TITLE
send_message is returning FirebaseError, Instead of raising Error. This makes try except impossible to catch error. Is this intentional or can we change it to raise error.

### ISSUE THREAD

**Issue by nitish9801** [xtrinch/fcm-django#215]
`      message.token = self.registration_id
        try:
            return messaging.SendResponse(
                {"name": messaging.send(message, app=app, **more_send_message_kwargs)},
                None,
            )
        except FirebaseError as e:
            self.deactivate_devices_with_error_result(self.registration_id, e)
            return e
`

**Comment by xtrinch** [comment]
It is probably a better pattern to raise the error, I agree with that. Although not a backwards compatible change

**Comment by xtrinch** [comment]
Yes I think raising error would be more appropriate

**Comment by mohitCodepy** [comment]
@xtrinch , Would love to work on this

**Comment by xtrinch** [comment]
> @xtrinch , Would love to work on this

Please do!

**Comment by mohitCodepy** [comment]
@xtrinch , Raised the PR review please https://github.com/xtrinch/fcm-django/pull/241

**Comment by xtrinch** [comment]
Resolved in https://github.com/xtrinch/fcm-django/pull/241
