### ISSUE TITLE
How to register ios devices?

### ISSUE THREAD

**Issue by mascDriver** [xtrinch/fcm-django#216]
I saw the firebase not have support for safari and safari ios, but in the options device fmc-django have option for register devices ios, how do due this?

**Comment by merwok** [comment]
Wouldn’t these use the `web` device type, and be handled with web push notification?

**Comment by mascDriver** [comment]
i dont know, but my question is if have example for register the safari ios for receive notification, i saw in various post on stackoverflow is not possible use ios with firebase then my question if anyoone here got to work on ios

**Comment by merwok** [comment]
ios means ios phone, not a browser!

**Comment by mascDriver** [comment]
alright, then need develop in sdk and send for api fcm-django? because have possibility for use pwa/twa simulate native app, but the code is compile on browser

**Comment by xtrinch** [comment]
You can use this package in any browser that supports web push notifications - you can see a javascript example at https://github.com/xtrinch/fcm-django-web-demo
