### ISSUE TITLE
Sound and Badge not working when notification arrives in IOS

### ISSUE THREAD

**Issue by chrislumber** [xtrinch/fcm-django#226]
Hi!!!

I'm using the following code to send a push notification to a user:

device = FCMDevice.objects.filter(user=post.author)
device.send_message(Message(notification=Notification(title='Some Text Title', body='Some Text')))

The notification is sent, the problem is that the Notification is arriving with no sound and no badge.

Do you know how to fix this? or If I have to change the code?

Thank you very much!!

**Comment by phudinhtruongk18** [comment]
Same here

**Comment by phudinhtruongk18** [comment]
> Same here
Solved that with bellow code here 

from firebase_admin.messaging import Message, Notification, APNSConfig, APNSPayload, Aps

        devices.send_message(
            message=Message(
                data=message.data,
                notification=Notification(
                    title=message.title,
                    body=message.content,
                    img=img,
                ),
                apns=APNSConfig(
                    payload=APNSPayload(
                        aps=Aps(
                            badge=badge,
                            sound="default",
                        )
                    )
                ),
            ),

**Comment by IslamKolade** [comment]
Hello, please this seems a bit complex for me. Please can I get a tutorial or video to watch to get it right? Thanks.

**Comment by phudinhtruongk18** [comment]
> Hello, please this seems a bit complex for me. Please can I get a tutorial or video to watch to get it right? Thanks.

you might want to check 
https://github.com/xtrinch/fcm-django/blob/112b908982518e4953e17050e1fc6d0354ce4974/fcm_django/models.py#L123
and 
https://github.com/firebase/firebase-admin-python/blob/f0865f7493a2c642d2e551efdf19da1e53c1a8c3/firebase_admin/_messaging_encoder.py#L26

hope it help

**Comment by xtrinch** [comment]
Closing as @phudinhtruongk18 provided the solution
