### ISSUE TITLE
Documentation about installing with pip seems to be broken on readthedocs

### ISSUE THREAD

**Issue by daniboygg** [xtrinch/fcm-django#227]
Reading the documentation in https://fcm-django.readthedocs.io/en/latest/ when you reach Setup part I see the following 

![image](https://user-images.githubusercontent.com/50702276/219587739-6012a961-8bb1-4c23-b202-6cc60fa24014.png)

I'm using the latest version of Chrome and Firefox. However in the Readme of the project I can see it without problem

I'm the only one with this issue?

**Comment by xtrinch** [comment]
I see the full documentation on read the docs

**Comment by daniboygg** [comment]
I'm using the chrome on windows Version 110.0.5481.104 (Official Build) (64-bit), I've refreshed the cache and is still is missing. I inspect the html code and it seems to be missing some part. 

![image](https://user-images.githubusercontent.com/50702276/219592125-2f0ca66c-400d-42ba-bca3-abfb9b561b86.png)

I leave it here, just in case someone has the same problem.

**Comment by xtrinch** [comment]
Fixed in 1.0.13
