### ISSUE TITLE
Backward compatible Updates!!!!!

### ISSUE THREAD

**Issue by alimirjahani7** [xtrinch/fcm-django#235]
Thanks for making registeration_id unique in a minor version update that will fail other developers works
Very professional.

**Comment by xtrinch** [comment]
Could have gone with a major version update but I didnt view this as backwards incompatible as all you need is to run an sql query to clean up the duplicates which you should not have in the first place..

**Comment by alimirjahani7** [comment]
Sorry if I were rude, I was a little angry at the moment
The problem was we didn't expect there to be a migration like this that make CI/CD fail
and that takes some times and downtime to fix ( as I had deploy front-end and back-end together the front-end deploy run successfully and back-end failed )
