### ISSUE TITLE
Conflicting migrations detected

### ISSUE THREAD

**Issue by kristjanr** [xtrinch/fcm-django#24]
Upon applying migration, I get the message:
`CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0003_auto_20170502_0353, 0003_auto_20170313_1314 in fcm_django).
To fix them run 'python manage.py makemigrations --merge'
`

Probable fix: Shouldn't the 
https://github.com/xtrinch/fcm-django/blob/master/fcm_django/migrations/0003_auto_20170313_1314.py#L11
 be referring to the previous migration?

**Comment by xtrinch** [comment]
I believe you must have run migrate in the package version where this migration was actually missing. It has been fixed in later versions. I think removing your migration file should work.

**Comment by kristjanr** [comment]
Thank you so much for the fast reply!
