### ISSUE TITLE
[Question] How does this relate to https://github.com/jleclanche/django-push-notifications?

### ISSUE THREAD

**Issue by gabn88** [xtrinch/fcm-django#25]
This package seems to have a common base, but it is also more up-to-date?

Especially the use of FCM makes it easier to integrate for both Android an iOS I think?

Just curious as I'm planning to add notification support to my app soon.

**Comment by xtrinch** [comment]
I developed this library as a sort of fork of django-push-notifications, back when it had no support for FCM yet. It now also supports FCM. 

All in all, it is your choice. I update this library regulary and make sure I try to fix all issues and respond to enhancement requests. Always open to new features! I believe, however, the community at django-push-notifications is also very active and does the same. :)
