### ISSUE TITLE
Compatibility with Python 3.11 and Django 4.2

### ISSUE THREAD

**Issue by LizaMary13** [xtrinch/fcm-django#253]
Hi, I am new to fcm-django and am working on a project that had been using Python 3.5, Django 1.11 and fcm-django 0.2.11.
The fcm_send_bulk_message and fcm_send_message functions of the fcm module were used in that project. However on upgrading to Python 3.11 and Django 4.2, and installing latest fcm-django version (2.0.0), it was found that the following error was thrown:

Import "fcm_django.fcm" could not be resolvedPylancereportMissingImports
(module) fcm_django

The line of code that threw this error was:
from fcm_django.fcm import fcm_send_message

My queries are:
1) Can we use fcm-django version 0.3.11 with Django 4.2 and python 3.11?
2) If they're not compatible, what is the alternative to this? I cannot find the fcm module in fcm-django versions after 0.3.11. Has it been removed and what are the alternatives that I can follow?

**Comment by xtrinch** [comment]
Afraid not. You'll have to upgrade your python version or keep using the old version.
