### ISSUE TITLE
Deprecated send_all() and send_multicast() methods

### ISSUE THREAD

**Issue by Karol-Grabczak** [xtrinch/fcm-django#255]
According to https://firebase.google.com/support/release-notes/admin/python

send_all() and send_multicast() APIs are now deprecated. Use send_each() and send_each_for_multicast() APIs instead.

**Comment by xtrinch** [comment]
Thanks @Karol-Grabczak, labeled as fix next release

**Comment by andriusbalcikonis** [comment]
@xtrinch Is there an estimated time for next release?

**Comment by welshrat77** [comment]
AS above, any idea if this will be fixed soon. Apologies, appreciate its not me doing the work

**Comment by blazek** [comment]
Great! Thanks.

Are you planning a release before June 20, 2024.

**Comment by xtrinch** [comment]
See 2.1.0
