### ISSUE TITLE
set badge count dynamically by user

### ISSUE THREAD

**Issue by sean-seunghyun** [xtrinch/fcm-django#256]
Hello.
I want to set the badge count to the number of messages the user has when send_message to the Device QuerySet. How should I implement this?

**Comment by metalaureate** [comment]
I have the same question. The FCM documentation says it is possible (https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support ) but I can find no reference to this common use case in FCM-Django documentation.

**Comment by metalaureate** [comment]
I got it to work partially on iOS by using these undocumented classes, but then encountered a lot of weird bugs with inactive tokens that might be unrelated.

```
from firebase_admin.messaging import Message, Notification, Aps, ApsAlert,APNSConfig,APNSPayload

# Create APS alert and APS data for iOS
        aps_alert = ApsAlert(title=title, body=body)
        aps = Aps(alert=aps_alert, badge=badge)
        apns_payload = APNSPayload(aps=aps)
        apns_config = APNSConfig(payload=apns_payload)

        # Create the message with APNS configuration
        msg = Message(
            apns=apns_config,
            notification=Notification(title=title, body=body, image=image),
            data=data
        )
       ```

**Comment by xtrinch** [comment]
For all options that you can pass to Notification(), see https://firebase.google.com/docs/reference/admin/python/firebase_admin.messaging
There you can find parameter notification_count:

> notification_count – Sets the number of items this notification represents. May be displayed as a badge count for Launchers that support badging. See NotificationBadge https://developer.android.com/training/notify-user/badges. For example, this might be useful if you’re using just one notification to represent multiple new messages but you want the count here to represent the number of total new messages. If zero or unspecified, systems that support badging use the default, which is to increment a number displayed on the long-press menu each time a new notification arrives.

So you would basically do e.g.
```
notification = Notification(title=title, body=body, notification_count=123)
FCMDevice.objects.send_message(
    Message(notification=notification)
)
```
