### ISSUE TITLE
[Question] Problems while running migrations

### ISSUE THREAD

**Issue by dishapatil** [xtrinch/fcm-django#26]
Hi @xtrinch ,

When we run migrations, it shows 
```
Running migrations:
  Applying fcm_django.0003_auto_20170313_1314... OK
```
Looking into the table- django_migrations, it shows that only the migration 0003_auto has run.
Migration 0001_initial and 0002_auto do not run at all.

Hence, there is no table created in my DB as well. 

What can be the solution to this?

**Comment by xtrinch** [comment]
I'm sorry but I am having a hard time imagining this example - how can an alter field migration run, when the underlying migrations creating the table have not run? 

Do you get errors upon migrate? Do you get errors upon using fcm_django?

Also could you please paste which version of python & fcm django you are using?

**Comment by dishapatil** [comment]
Worked when I changed the database connection to a new one. 

There must have been a problem in the database it was pointing to. 
Thanks. :)
