### ISSUE TITLE
Changes related to the firebase API migration (batch send)

### ISSUE THREAD

**Issue by illymarev** [xtrinch/fcm-django#261]
Hello! 
The firebase announced a large migration on June 20th, 2024. One affected area is the bulk send API (https://firebase.google.com/support/faq#fcm-23-deprecation), which is currently utilized by the fcm-django.
I noticed that you have recently made this change on the master branch. Could you specify the approximate timeline for when it will be available in a stable version on pypi? 
Thank you

**Comment by xtrinch** [comment]
I'll see to it by the end of the week

**Comment by xtrinch** [comment]
See 2.1.0
