### ISSUE TITLE
FCMDevice QuerySet does not work with send_message due to `send_all` usage

### ISSUE THREAD

**Issue by nguyenvanduc208** [xtrinch/fcm-django#273]
### Description

When calling `send_message` on an `FCMDevice` QuerySet, it doesn't send notifications because internally it uses `send_all`, which fails with QuerySets. After modifying the core to replace `send_all` with `send_each`, the notifications are delivered successfully.

Steps to reproduce:

1. Retrieve an `FCMDevice` QuerySet:
    ```python
    devices = FCMDevice.objects.filter(user__is_active=True)
    ```

2. Call `send_message`:
    ```python
    devices.send_message(title="Notification Title", body="Notification Body")
    ```

3. No notifications are sent.

4. Modify the core to use `send_each`:
    ```python
    for device in devices:
        device.send_message(title="Notification Title", body="Notification Body")
    ```

5. Notifications are successfully delivered.

Suggested fix: Replace `send_all` with `send_each` in the core, or make `send_all` handle QuerySets correctly.

**Comment by samuel-andres** [comment]
Why did you closed this issue? It wasn't fixed.

**Comment by samuel-andres** [comment]
This is fixed since https://github.com/xtrinch/fcm-django/releases/tag/2.1.0 :)
