### ISSUE TITLE
Need "content_available" param to use Data message on iOS

### ISSUE THREAD

**Issue by vadim-bulochnik** [xtrinch/fcm-django#3]
Hi!

Thanks for the great extension!

In order to use Data Messages only (without Notification Message) for both Android and iOS need to add "content_available" param. Please check out documentation about this param here: https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json
Also, there is notice about this param here: https://firebase.google.com/docs/cloud-messaging/concept-options

> Note: If you want to send messages consisting of only custom key-values to an iOS device when the app is in the background, set custom key-value pairs in the data key and set content_available to true.

Best regards,
Vadim

**Comment by vadim-bulochnik** [comment]
Sorry to disturbing you for nothing.
I've found in your extension that you add 'content_available' param in case of sending only custom data messages.

Sorry again. And thanks.

Best regards,
Vadim

**Comment by xtrinch** [comment]
Okay, cool. Thanks anyway :)
