### ISSUE TITLE
How to structure the the notification correctly?

### ISSUE THREAD

**Issue by connercms** [xtrinch/fcm-django#30]
We are using your library in conjunction with react-native-fcm library. The docs for react-native-fcm says it expects a payload that looks like the following
```
{
    "to":"your_fcm_device_token",
    "notification": {
        "title": "hello",
        "body": "yo"
    },
    "priority": "high"
  }
```

We are structuring are message as follows, but are receiving an error on the notification field.
```
.send_message(
	to=“fcm_device_token”,
	content_available=True,
	notification={
		“title”: value, 
		“body”: value,
		“click_action”: “fcm.ACTION.HELLO”,
	},
	priority=“high”
)
```

Any help would be appreciated

**Comment by xtrinch** [comment]
Can you paste the error you are getting?

**Comment by xtrinch** [comment]
Closing, as there is no response. Feel free to comment further.
