### ISSUE TITLE
How to Send Topic messages

### ISSUE THREAD

**Issue by claudiocleberson** [xtrinch/fcm-django#31]
Hi,

I quick question, I couldn't find any way to Send notification to a specific topic. is there any way to do that?

"to": "/topics/general",
 "data": {
        "message" : "my",
        "other_key" : true,	
        "body":"teste number 3"
	},
    "notification" : {
    "title" : "FCM Message",
    "body" : "Still getting pushs",
     "content_available" : true
	},
     "priority": "high"

**Comment by xtrinch** [comment]
That is a feature yet to be implemented. Open to pull requests, otherwise will get to it when I have more time :)

**Comment by Bartvds** [comment]
Any word on this? Seems quite an important part of FCM. I see pyfcm has support for topics (https://github.com/olucurious/PyFCM/blob/20be33c28fa485068165c424eb178eba553b889c/pyfcm/fcm.py#L189), so does this need anything more then a wrapper in fcm_django/fcm.py ?

**Comment by xtrinch** [comment]
Yeah, a wrapper should be enough.

**Comment by xtrinch** [comment]
Resolved in 0.2.18
