### ISSUE TITLE
Wrong database schema when USER_MODEL setting not equal to AUTH_USER_MODEL

### ISSUE THREAD

**Issue by maximlomakin** [xtrinch/fcm-django#32]
I change user foreign key in device model using "USER_MODEL" setting. But in the database constraint still limit foreign key by "AUTH_USER_MODEL". Rerun of migrations don't help.

Problem in 0001_initial migration. There is hardcoded "AUTH_USER_MODEL" in it.
https://github.com/xtrinch/fcm-django/blob/master/fcm_django/migrations/0001_initial.py#L27

**Comment by xtrinch** [comment]
I am not sure why exactly is this necessary, you will find in official django docs that changing the auth user model is via AUTH_USER_MODEL settings variable.

**Comment by maximlomakin** [comment]
This is necessary if you need to change model to which device's user field refer without changing AUTH_USER_MODEL. I.e to bind the device to non-user model. I think for this we need separate settings variable in the FCM_DJANGO_SETTINGS.

**Comment by xtrinch** [comment]
Alright, if the point is to point to a non-user model, perhaps we should name the variable differently. Something like DEVICE_FOREIGN_KEY. Although is there a specific reason you need this? I'm just trying to envision why this would be necessary

**Comment by maximlomakin** [comment]
In my application I need device-session-user schema.

I don't think that renaming of the variable is a good idea. With that we should rename field too. In the end, this will create problems with backward compatibility or clarity. And this problems cannot be resolved within small pull request.

**Comment by sanjayMantati** [comment]
relation "fcm_django_fcmdevice" does not exist
what could be it's reason?

**Comment by salberin** [comment]
> In my application I need device-session-user schema.
> 
> I don't think that renaming of the variable is a good idea. With that we should rename field too. In the end, this will create problems with backward compatibility or clarity. And this problems cannot be resolved within small pull request.

I'm having the exact same problem. For us, this creates a circular dependency between the model and our application: we extend the FCMDevice model, but the user-model on the FCMDevice needs to point to another model in our application. Hence, an circular dependency exists.

**Comment by zt-initech** [comment]
Everything is fine except that the file `migrations/0001_initial.py` uses `settings.AUTH_USER_MODEL` instead  of `FCM_DJANGO_SETTINGS['USER_MODEL']`, so running `./manage.py migrate` creates the `fcm_django_fcmdevice` database table with the wrong foreign key (in case `FCM_DJANGO_SETTINGS['USER_MODEL']` is not the same as `settings.AUTH_USER_MODEL`).

Please fix this.

**Comment by xtrinch** [comment]
Resolved @ https://github.com/xtrinch/fcm-django/pull/33
