### ISSUE TITLE
the message has been delivered, But why Error has occured?

### ISSUE THREAD

**Issue by yenoss** [xtrinch/fcm-django#34]
```
Traceback (most recent call last):
  File "/home/--/--/--/.py", line 182, in send_push_to_user
    device.send_message(title, content)
AttributeError: 'NoneType' object has no attribute 'send_message'
```

any help would be appreciated.

**Comment by xtrinch** [comment]
More info about package & python versions required.

**Comment by yenoss** [comment]
okay, here!

fcm-django==0.2.11
Python 3.5.2

Please comment to me, if you need more.

**Comment by xtrinch** [comment]
pyfcm version also please

**Comment by yenoss** [comment]
of course.

pyfcm==1.3.1

**Comment by xtrinch** [comment]
I think you will have to examine your own code further, because the error is actually in your code.

**Comment by yenoss** [comment]
Im rechecking my Code

and I found the wrong code in service business logic.

Thank you for your kindness.

have a good day!
