### ISSUE TITLE
Problem when logging in with another account

### ISSUE THREAD

**Issue by Almaral-Engineering** [xtrinch/fcm-django#35]
I have a problem when I follow next steps

1.- When I logout from account A and login with account B, A stays but is disabled

2.- I logout from B and want to login on A again, A already exists but is disabled so I get a conflict and A is not re-enabled

3.- B is disabled because I tried to login with A so now both are disabled and I am not getting any fcm

Is there a way of make both work for the same device or delete the device which is logging out? any of them would be useful

**Comment by xtrinch** [comment]
Define what 'disabled' means for you. You can automatically delete inactive devices via this package's setting, but inactive device might not mean the same as logged out device. It would be best if you manually deleted the FCMDevice entry upon logging out, assuming you probably have an HTTP endpoint for logging out.

**Comment by Almaral-Engineering** [comment]
Thanks, what I did was removing the device from the db when the user logs out
