### ISSUE TITLE
Multiple devices with same account

### ISSUE THREAD

**Issue by Almaral-Engineering** [xtrinch/fcm-django#36]
Is it possible to have multiple devices with the same email so all of them receive the fcm's?

**Comment by xtrinch** [comment]
Sure, why not? Just create multiple FCMDevice instances for the same user.

**Comment by Almaral-Engineering** [comment]
The thing is, when I create a FCMDevice for a user, the other gets overwritten, so only one receive notifications at a time, I have this in settings:

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": os.environ['FCM_SERVER_KEY'],
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": True,
}
