### ISSUE TITLE
Unreliable

### ISSUE THREAD

**Issue by Shanlon** [xtrinch/fcm-django#37]
I have recently set up FCM with DRF and unfortunately it is very unreliable. 

I have followed all of the directions, I have done extensive testing, and made sure this is not a user level issue. I am not sure if something is up with the source code, or with FCM but messages are sent after a long delay or never sent at all. Sometimes only 1/10 of the users will get the notifications where as 10/10 will get them.

Since there are these issues it is very hard to continue to use this framework or to continue to use firebase cloud messaging. 

We are using this service paired with a iOS mobile app. Yes we are storing the correct device Registration tokens since this is given to us from firebase. All of the certificates are correct.

My questions are:
Is FCM not reliable for a production level app used at a large scale? 
Are there plans for more testing using this framework with a larger data set?

Cheers!

**Comment by xtrinch** [comment]
send_message functions from this library models return a result. Have you by any chance tried to analyse the response from FCM that is returned in this result? It should tell you enough data about why and to which devices the messages were not sent. Let me know.

**Comment by xtrinch** [comment]
I've updated pyFcm version, I believe there have been some fixes made there
