### ISSUE TITLE
Unable to receive the message from server

### ISSUE THREAD

**Issue by dungeonpp** [xtrinch/fcm-django#38]
On sending message/notification for very first time , it displays success and returns the message id back as a response:

>>> device.send_message({"notification":{"title": "SAMS : Profits raised by 10%", "body": "Hello DRasF"}})
[{'failure': 0, 'canonical_ids': 0, 'success': 1, 'multicast_id': 6814660615641113568, 'results': [{u'message_id': u'0:1510052176239497%2fd9afcdf9fd7ecd'}]}]

While sending it the second time I receive this error:
 
>>> device.send_message({"notification":{"title": "INFY : First Successful Trade", "body": "Hello DRasF"}})
[{'failure': 1, 'canonical_ids': 0, 'success': 0, 'multicast_id': 4697703935609967698, 'results': [{u'error': u'NotRegistered'}]}]

Could you please help me out. Also the documentation is insufficient to address this issue.

**Comment by xtrinch** [comment]
This seems like a firebase issue, not with this library.
