### ISSUE TITLE
[Issue] FCM table saving id of user instead of username

### ISSUE THREAD

**Issue by uber1geek** [xtrinch/fcm-django#39]
I have a  custom user model, however, when i register a device, the fcm-django model registers the id column of the related username or (partner_id in my case) to the user_id  column.

I want the user_id to have username and not the id of the particular username

I have attached screenshots of the tables, how can i fix this?  I need to send push notifications to a particular username(partner_id) which is my unique identifier for data across other tables.

PS: partner_id == username.

My users table:
![screen shot 2017-11-28 at 4 12 27 pm](https://user-images.githubusercontent.com/8023116/33316168-07928204-d459-11e7-9151-a3b578559213.png)

fcm-django table:
![screen shot 2017-11-28 at 4 12 58 pm](https://user-images.githubusercontent.com/8023116/33316174-0e88fc8c-d459-11e7-8f1c-152db6f94d5c.png)

**Comment by xtrinch** [comment]
Unique identifier or also primary key?
