### ISSUE TITLE
No end point for updating registration_id

### ISSUE THREAD

**Issue by ToniNgethe** [xtrinch/fcm-django#45]
Tried finding an end point for updating the fcm token incase it changes but could not find it. kindly assist

**Comment by xtrinch** [comment]
PUT/PATCH request to the same endpoint you use for registering devices?

**Comment by ToniNgethe** [comment]
Yes, i tried that but it doesn't update.

**Comment by xtrinch** [comment]
What does it return?

**Comment by ToniNgethe** [comment]
the entire model. Other fields such as name are updated but the
registration_id isn't updating

**Comment by ToniNgethe** [comment]
I had to create my own end points to achieve want i wanted. Anyway thank you
