### ISSUE TITLE
iOS deviice deactivated automatically

### ISSUE THREAD

**Issue by ManojDatt** [xtrinch/fcm-django#5]
fcm_django, works well on Android device and iOS simulator for notification.
But on iOS device `active become False` 

> (iOS device deactivated)

automatically. and no notification receives 
Can any one please help me.

**Comment by xtrinch** [comment]
I don't think notifications work in iOS simulator, do they?

In any case, are you sure all your certificates are configured correctly in the firebase console? Because device is marked as inactive if isn't able to receive messages correctly. Try sending a test message from django admin via admin actions, and see what the error message says.

**Comment by ManojDatt** [comment]
Yes you are right certification was not correct.
after adding .p12 file on production we are ready to go to receive
notification..


Thanks

**Comment by ManojDatt** [comment]
Junglee Rummy

             

    
                 
                        
                        	
                        	
							
							The Fastest Growing Rummy Site in India 
							
                              
	                
	            
         
    
  
    
        
        
          Hi xtrinch/fcm-django,
         manojdutt has invited you to play rummy at JungleeRummy.com!
        
        
         
        
        
            
               Register at the best rummy site and experience the real fun of playing rummy with your friends. We offer you the most genuine rummy experience through a collection of free and cash games . Go Play Now!
			   
			   Click on the following URL or copy and paste it into your browser to join: 
                https://www.jungleerummy.com/promotion/refer?refid=2006676
                
            
        
        
          
              100% Welcome Bonus
              
              As you are a friend of manojdutt, we are offering you an exclusive bonus! Register with JungleeRummy.com as a VIP Player and earn extra money – Use the Bonus Code WIN1500 while making your first deposit and get 100% Bonus up to Rs.1500!
          
        
        
           See you at the tables!

        Customer Support Team 
        www.JungleeRummy.com

        
             
      
    
  
    
					
						
						  
						    Refer & Win | Safe & Secure | Privacy Policy  | Testimonials
						    
						  
						
					
				


		        
		          
		            
		              
		                
		              
		            
		          
		        


		        
		          
		            
						
							 © Junglee Games Pvt. Ltd.

**Comment by Almaral-Engineering** [comment]
In am facing the same issue, I have the certificates and I am receiving the push notifications when sent directly from the Firebase console, but when I send them via my server the device gets deactivated

**Comment by jimmycrowdbotics** [comment]
hi @xtrinch , i am facing the same issue as @hackaprende facing. right now is there any solution.
package is working fine with android devices.
