### ISSUE TITLE
Get user device(s)

### ISSUE THREAD

**Issue by Bernix01** [xtrinch/fcm-django#52]
I see there's no `related_query_name` (correct me if I'm wrong)

**Comment by xtrinch** [comment]
Correct me if I'm wrong, but having related_query_name would allow you to filter users by specific device?

**Comment by Bernix01** [comment]
Yes, and if there's single device per user it would allow to directly get the user of any given device.

**Comment by xtrinch** [comment]
True. Reasonable request. Coming soon :)

**Comment by Andrew-Chen-Wang** [comment]
@xtrinch bump

**Comment by xtrinch** [comment]
Fixed in https://github.com/xtrinch/fcm-django/commit/d0b24342923e2d5d5b7be6910ab7996d6f09dcec
