### ISSUE TITLE
New device auto set active=False

### ISSUE THREAD

**Issue by peeomid** [xtrinch/fcm-django#53]
Hi,

I'm getting a weird issue, can't seem to find out the reason why, as the default value in device model of active field is set to True.
However when I try to create a new device (without explicitly pass `active`), `active` is automatically set to False.

Seems like `extra_kwargs = {"active": {"default": True}}` doesn't work as expected. Only when `active` is added to `read_only_fields` then it works.

Anyone get the same issue?
Thanks

**Comment by peeomid** [comment]
Just a side note, `rest_framework.py`, under `DeviceViewSetMixin`, there's this:

```
if (SETTINGS["ONE_DEVICE_PER_USER"] and
                    self.request.data.get('active', True)):
                FCMDevice.objects.filter(user=self.request.user).update(
                    active=False)
```
In case `active` is not pass, then that `self.request.data.get('active') will give back None, which will make the condition False right?

**Comment by ijajmulani** [comment]
I'm also facing same issue.

@xtrinch  extra kwargs sets active to true using below code.

in `DeviceSerializerMixin`'s `Meta` class
`extra_kwargs = {"active": {"default": True}}`


but `extra_kwargs` gets override when 
`FCMDeviceSerializer`'s `Meta` class  inherit `DeviceSerializerMixin.Meta`

So I think below code might need some changes
```
# Serializers
class DeviceSerializerMixin(ModelSerializer):
    class Meta:
        fields = (
            "id", "name", "registration_id", "device_id", "active",
            "date_created", "type"
        )
        read_only_fields = ("date_created",)
        extra_kwargs = {"active": {"default": True}}

class FCMDeviceSerializer(ModelSerializer, UniqueRegistrationSerializerMixin):
    class Meta(DeviceSerializerMixin.Meta):
        model = FCMDevice
        extra_kwargs = {"id": {"read_only": False, "required": False}}
```

So when I removed `extra_kwargs` from `DeviceSerializerMixin.Meta` class and added it to 
`FCMDeviceSerializer.Meta ` in below way 


```
# Serializers
class DeviceSerializerMixin(ModelSerializer):
    class Meta:
        fields = (
            "id", "name", "registration_id", "device_id", "active",
            "date_created", "type"
        )
        read_only_fields = ("date_created",)

class FCMDeviceSerializer(ModelSerializer, UniqueRegistrationSerializerMixin):
    class Meta(DeviceSerializerMixin.Meta):
        model = FCMDevice
        extra_kwargs = {"id": {"read_only": False, "required": False}, "active": {"default": True}}
```
Then it works.

If you are agree with this change, I would love to make pull request.

**Comment by kz26** [comment]
I'm also experiencing this issue on the latest version 0.2.19.
