### ISSUE TITLE
Sending messages in bulk not working

### ISSUE THREAD

**Issue by AlexisCaffa** [xtrinch/fcm-django#56]
Simply don't send. No errors, no messages.
```python
# This not work:
devices = FCMDevice.objects.all():
devices.send_message('Hello', 'World')

# This ugly solution yes, works
for device in FCMDevice.objects.all():
    device.send_message('Hello', 'World')
```

**Comment by xtrinch** [comment]
Which version of fcm_django &django & python?

**Comment by AlexisCaffa** [comment]
Python == 3.5.2
Django == 1.11.11
fcm-django == 0.2.16

**Comment by xtrinch** [comment]
Interestingly enough it works at all, with such an old version of django :) This package supports 1.8+

**Comment by AlexisCaffa** [comment]
:laughing: 1.**11**.11 :arrow_right: 11 > 8

**Comment by xtrinch** [comment]
Oh, sorry. My mistake.

Well I just tested it with 1.11.11 with django admin actions and python 2.7 and it works. Maybe the issue is the python version.

**Comment by AlexisCaffa** [comment]
Works perfectly!!
:sweat: My code set active field to False 
I'm so sorry
