### ISSUE TITLE
abstract FCMDevice

### ISSUE THREAD

**Issue by alfaro28** [xtrinch/fcm-django#57]
I currently want to extend FCMDevice to use BigAutoField instead of regular AutoField, so I was thinking if its posible to move all the code in  FCMDevice to "AbstractFCMDevice" and make FCMDevice inherit from AbstractFCMDevice this way FCMDevice will work out of the box as it is now, but with the flexibility to modify it if necessary

**Comment by alfaro28** [comment]
@xtrinch any feedback on this?

**Comment by klorophyl** [comment]
Would be awesome if this PR was merged, would like to add db_index=True to some fields, it makes my db lag

**Comment by xtrinch** [comment]
Released in 0.2.19
