### ISSUE TITLE
send_message returns InvalidRegistration

### ISSUE THREAD

**Issue by pacocampo** [xtrinch/fcm-django#59]
Hi Guys!

For unknown reason when I try to send a message I have this response:
{'multicast_ids': [7427671007952509285], 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results': [{'error': 'InvalidRegistration'}], 'topic_message_id': None}

My django settings: 
`FCM_DJANGO_SETTINGS = { 
    "FCM_SERVER_KEY": "<API_KEY>",
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": False, 
 }`

I'm trying to send this message:
`device.send_message("title", "hello firebase")`

I'm working with:
Django = 1.11.1
fm-django = 0.2.18

Could you help me please?

**Comment by Myzel394** [comment]
Did you find a solution to this? I'm facing the same issue.
