### ISSUE TITLE
Return Type Error from models

### ISSUE THREAD

**Issue by haruair** [xtrinch/fcm-django#6]
I'm having an issue with send_message. In https://github.com/xtrinch/fcm-django/blob/master/fcm_django/models.py#L55 , a return value from FCM is changed I guess.

```
Internal Server Error: /admin/notification/
Traceback (most recent call last):
  File "/Users/edward/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/edward/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/edward/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edward/app/admin/views.py", line 27, in PushNotificationView
    body=request.POST.get('body', None),
  File "/Users/edward/.venv/lib/python3.5/site-packages/fcm_django/models.py", line 56, in send_message
    for (index, item) in enumerate(result['results']):
TypeError: list indices must be integers or slices, not str
```

Python 3.5.1 (default, Aug 15 2016, 18:12:18) 

```
Django==1.10.3
django-braces==1.10.0
django-crispy-forms==1.6.1
django-filter==1.0.0
django-oauth-toolkit==0.11.0
django-widget-tweaks==1.4.1
djangorestframework==3.5.3
drfdocs==0.0.11
fcm-django==0.2.3
Markdown==2.6.7
oauthlib==1.1.2
pyfcm==1.2.1
requests==2.12.4
six==1.10.0
```

**Comment by xtrinch** [comment]
I see you are using a newer version of pyfcm, it seems that the responses from that library have changed since 1.0.7, which this library depends on. I would suggest that unless you need the newer version of the pyfcm library, you uninstall it and let pip install the older version as a dependency.

Or am I wrong and was the newer version of pyfcm somehow installed automatically?

**Comment by haruair** [comment]
Yes, I tried to use latest pyfcm because the old deps have a same issue. If I change the line to `enumerate(result)`, it's working fine but I'm not sure this is the right solution.

**Comment by xtrinch** [comment]
Are you sure the old version has the same issue? We are successfully using
this library and this function in production version of some apps. Can you
perhaps try printing the result variable and pasting it here with the old
version?

**Comment by xtrinch** [comment]
This issue was caused becacuse of inappropriate pyfcm version.

Newest version, 2.5.0 has a dependency on pyfcm 1.2.3 so please check that first. Closing.
