### ISSUE TITLE
Get Response from send_message()

### ISSUE THREAD

**Issue by Tindi** [xtrinch/fcm-django#60]
Hi! I love this library so far. I was wondering how I can get the response from send_message()? When I run it my notification is sent to my phone but I get an AssertionError:

`AssertionError at /api/job/notification/
Expected a 'Response', 'HttpResponse' or 'HttpStreamingResponse' to be returned from the view, but received a <type 'instancemethod'>`

I can catch it but I wanted to know what kind of response to expect from the function so I can log it. Any help would be appreciated.

**Comment by xtrinch** [comment]
The assertion error you are getting is in no way connected with fcm-django.

**Comment by xtrinch** [comment]
A dictionary with some data about the result of the sending
