### ISSUE TITLE
is_user_authenticated() throws exception

### ISSUE THREAD

**Issue by ijajmulani** [xtrinch/fcm-django#62]
<img width="1440" alt="screen shot 2018-05-25 at 1 50 11 am" src="https://user-images.githubusercontent.com/4729653/40511694-2b382ace-5fbe-11e8-82e5-8f6b04041e53.png">

When I make a request to register device above exception django throws.

Django version I use :
VERSION = (1, 11, 2, 'final', 0)

What happens:
  in `fcm-django/fcm_django/api/rest_framework.py`
 `is_user_authenticated()` function might be wrongly implemented.

**How to solve:**

For Django 1.10 +
`is_authenticated` is now an attribute

**Solution 1:**
we could use rest_framework's 
`from rest_framework.compat import is_authenticated`

and instead of `is_user_authenticated(user)` we could use `is_authenticated(user)`

**Solution 2**
we correct the `is_user_authenticated()` method below way: 

```
def is_user_authenticated(user):
    if  DJ_VERSION < (1, 10):
        return user.is_authenticated()
    return user.is_authenticated
```

Note: Please correct me if I am wrong.

**Comment by ijajmulani** [comment]
I would be happy to make PR.

**Comment by xtrinch** [comment]
Sure, PR's are always welcome

**Comment by ijajmulani** [comment]
Here is [PR](https://github.com/xtrinch/fcm-django/pull/63)

**Comment by xtrinch** [comment]
Dropping support for django versions below 1.8, closing issue
