### ISSUE TITLE
Is there a way to know the device type?

### ISSUE THREAD

**Issue by Almaral-Engineering** [xtrinch/fcm-django#66]
I want to send data message if the device is android and a notification message if it´s iOS, is there a way to get the device type after this:

`device = FCMDevice.objects.get(user=my_user)`

something like 
```
if device.type == "android"
    # Send a data message
elif device.type == "ios"
    # Send a notification message
```

**Comment by xtrinch** [comment]
There is a type field but you are responsible for filling it in when creating devices.

**Comment by Almaral-Engineering** [comment]
Ah yes, I know how I am going to to that, for other people who has the same issue:

```
device = FCMDevice.objects.get(user=my_user, type="android")

if device is not None:
    # Send a data message
else:
    device = FCMDevice.objects.get(user=my_user, type="ios")
    if device is not None:
        # Send a notification message
```
