### ISSUE TITLE
use another model instead of auth user

### ISSUE THREAD

**Issue by Mhs-220** [xtrinch/fcm-django#69]
hi
thanks for your great work
i set USER_MODEL in my source code (according to your code) and its seem to work ok but sometimes i get error and i think it depend on AUTH_USER
but im not wanna to send push to my auth user
how can i do it?

**Comment by Mhs-220** [comment]
i get this error when i try to sava a device
```
insert or update on table \"fcm_django_fcmdevice\" violates foreign key constraint \"fcm_django_fcmdevice_user_id_6cdfc0a2_fk_user_customuser_id\"\nDETAIL:  Key (user_id)=(204) is not present in table \"user_customuser\".\n
```
FYI, my auth model is "CustomUser" and my other user that i want to send push notification to them is "NormalUser"

**Comment by Mhs-220** [comment]
Im so sorry!
i forgot to makemigrations
all worked and fixed

**Comment by sreebash** [comment]
@Mhs-220  How did you do that? I have similar issue

**Comment by Mhs-220** [comment]
@sreebash It was four years ago, and I can't remember correctly. But I think that I forgot to `makemigrations` and `migrate`
