### ISSUE TITLE
FCMDevice.send_message() parameter missing for iOS Background notification and sound

### ISSUE THREAD

**Issue by henriquevelloso** [xtrinch/fcm-django#7]
Hello,
In iOS, to provide a background notification, the JSON sent to firebase MUST have a key `"content_available" : true`
and other issue there is no sound on notification.
this is my working json with sound and background notification for iOS.

```
{ 
   "data":{  
      "key":"..."
   },
   "content_available" : true,
   "notification":{ 
       "sound": "default",
       "title": "...",
       "body":"..."
   },
 "to":"..." 
}
```

**Comment by vadim-bulochnik** [comment]
Hi,

First, "content_available" is added in a library core. It's ok.
Second, about sound please check my issue: https://github.com/xtrinch/fcm-django/issues/4

Best regards,
Vadim

**Comment by xtrinch** [comment]
I've updated the sound and badge parameters and uploaded them to pypi, so try 0.2.4 for sound :) @vadim-bulochnik @henriquevelloso 

So @henriquevelloso you are not able to receive background notifications via this package?

**Comment by xtrinch** [comment]
Closing, feel free to comment if any additional information pops up.
