### ISSUE TITLE
Sometimes devices deactivate 

### ISSUE THREAD

**Issue by Almaral-Engineering** [xtrinch/fcm-django#70]
I have notice often some devices get deactivated and I have to activate them again manually, do you know why it could happen? What can cause a device to deactivate?

Is there a way to activate them programmatically? Like
```
device = FCMDevice.objects.filter(id=id)
if device.active == False:
    device.active = True
    device.save()
device.send_message(...)

```
Thanks for this library @xtrinch, you really rule!

**Comment by xtrinch** [comment]
No, them not having internet connection will not cause it to fail. More info can be found on google's fcm docs, as they will hold more specific information about which tokens are not valid.

**Comment by Almaral-Engineering** [comment]
But sometimes the isActive value gets set to false, like here:
![image](https://user-images.githubusercontent.com/5779511/63992091-d7325b80-caaf-11e9-81cf-70e84d3e742e.png)
The user is logged in and the app was not deleted, so what could cause that?

**Comment by refaelsommer** [comment]
We also have a serious problem and having the same issue, FCM tokens are being deleted and we have tested many times with users that have the app continuously installed, they are using the app and did not delete it, FCM is deleted and then they do not get push notifications anymore, this is really bad since we cannot re target the users by notifications.

**Comment by Almaral-Engineering** [comment]
@refaelsommer for you and others with the same problem, you can do this:

result = devices.send_message(data=data)
print(str(result))

And result is going to tell you why is deactivating

**Comment by dffpm** [comment]
Hi there!
We have faced with the same problem.

When user authorize, push notifications works short time, then later any push request from the backend to FCM gets response: [None, None]

We have release at the end of this week. But we can'y find any solution for solving this case..
Did someone found out what's happening?

**Comment by xtrinch** [comment]
What's the result of the suggestion @Almaral-Engineering gave?

**Comment by dffpm** [comment]
We get [None, None] when user made logout (user has no devices)
But user don't do any logouts and backend got [None, None] per request to FCM after some hours.
DELETE_INACTIVE_DEVICES = True
ONE_DEVICE_PER_USER = False

**Comment by xtrinch** [comment]
Disable the DELETE_INACTIVE_DEVICES and troubleshoot why they're supposedly "inactive"

**Comment by dffpm** [comment]
Ok, we have changed flags values into:
DELETE_INACTIVE_DEVICES = False
ONE_DEVICE_PER_USER = True

After testing push sending we have next:
looks fcm_send_message() works fine, it returns result:
{
    "multicast_ids": [
        xxxxxxxxxxxx
    ],
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "xxxxxxxxx"
        }
    ],
    "topic_message_id": null
}

But. Devices (iOS) does not receive the push. What way we should use troubleshooting now?

**Comment by xtrinch** [comment]
Sorry, but what is the original problem? 

Devices being deactivated or devices not receiving push notifications?

Because setting DELETE_INACTIVE_DEVICES to False should not change whether devices receive notifications or not

**Comment by dffpm** [comment]
Yeah, sorry, seems it is another problem.
Original problem (after troubleshooting) is: probably, library could remove device_id from the database.
After DELETE_INACTIVE_DEVICES was switched into False, we didn't see in logs [None, None],  all notifications were sent. (iOS device does not receive push notifications - it is another problem).

Right now we'll continue testing and waiting wrong responses. 

I have just 1 question now: Does the library have logic capable of deleting tokens without an explicit request or "sign out" logic?

**Comment by xtrinch** [comment]
No, you need delete them yourself, if the DELETE_INACTIVE_DEVICES is not enough (although it should be)

By the way, which version are you using?

**Comment by dffpm** [comment]
> No, you need delete them yourself, if the DELETE_INACTIVE_DEVICES is not enough (although it should be)
> 
> By the way, which version are you using?

0.2.21

**Comment by dffpm** [comment]
@xtrinch  Thank you so much! Problem was on our side, not in library. But your explanations helped us to solve it. Issue can be closed.
