### ISSUE TITLE
Can I use FCMDeviceAuthorizedViewSet to send message according the user logged in.

### ISSUE THREAD

**Issue by sanjayMantati** [xtrinch/fcm-django#74]
I am using DRF(Django Rest Framework) and fcm_django. 
My requrement: when user hit send message endpoint with desired params, fcm_django should send_messge only those devices that correspond to logged in user in Device_model table.

My question is can i use FCMDeviceAuthorizedViewSet  in this scenario. Because it has one method get_queryset() which gives only those records which corresponds to the logged in user.

**Comment by xtrinch** [comment]
Yes ofcourse you can!
