### ISSUE TITLE
Can't set android_channel_id

### ISSUE THREAD

**Issue by swaterfall** [xtrinch/fcm-django#86]
There doesn't appear to be a way to set the android_channel_id as available in PyFCM: https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L94

This is required for the latest version of android so push notifications are failing.

**Comment by xtrinch** [comment]
This should certainly be fixed in next release

**Comment by craiglabenz** [comment]
Any update on this issue?

**Comment by chkdmin** [comment]
Any update or another way on this issue?
