### ISSUE TITLE
Question about returning value from send_message when registration_ids is empty

### ISSUE THREAD

**Issue by SerhiyRomanov** [xtrinch/fcm-django#89]
Hi all! 
I has a question about this line of code https://github.com/xtrinch/fcm-django/blob/master/fcm_django/models.py#L66

Why it should be returned as list? 
As i see, FCM API always returns a dict ([docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref#interpret-downstream))

I guess, the better option could return it like dict
`return {'failure': len(self), 'success': 0}`

What do you think?

**Comment by xtrinch** [comment]
Yes but that breaks backwards compatibility, so it would need special handling

**Comment by SerhiyRomanov** [comment]
@xtrinch I made #117 for this issue.
It would be nice to avoid copy-paste response structure from PyFCM in this line https://github.com/xtrinch/fcm-django/pull/117/files#diff-491fcfd5871964208672e55b84c7106aR6
But it's require changes in PyFCM

**Comment by xtrinch** [comment]
Fix merged with #117
