### ISSUE TITLE
Notification doesn't wake up device, doesn't vibrate or sound when app is in background/killed

### ISSUE THREAD

**Issue by renato-bvdash** [xtrinch/fcm-django#93]
I have tested sending messages from Firebase directly and it's the same result.

- I have added a `data={ "test": "test" }` and `sound="default"` payload as many stackoverflow ansers suggest but nothing.
- GCM messages tests are noisy by default.
- I am on react native, so I can't do some of the Java hacks other online solutions suggest.
- Doing [this](https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages#4) changes nothing.

Any help would be appreciated.

**Comment by priyadhoundiyal** [comment]
Hey @renato-bvdash, were you able to find a solution to this?
Looping @xtrinch in - Thanks for the library! Is there probably some setting we're missing that's causing this?

**Comment by renato-bvdash** [comment]
I have not solved it yet @priyadhoundiyal :(

**Comment by renato-bvdash** [comment]
@priyadhoundiyal I was using django-push-notifications which is a library that has fallen out of maintenance. Once I switched back, I started getting vibrating notifications.
Then I realized I had the device on mute for notifications. Once I upped the volume for notifications, I started getting the sound.
Make sure that's not the case for you.
