### ISSUE TITLE
Key error on token update (patch)

### ISSUE THREAD

**Issue by M-Ghasemi** [xtrinch/fcm-django#94]
A KeyError occurs when a patch update is requested, and either of "active" or "registration_id" is not provided.
/devices/registration_id/
method: PATCH

**Comment by AlexisCaffa** [comment]
Error at this line https://github.com/xtrinch/fcm-django/blob/master/fcm_django/api/rest_framework.py#L67

Internal Server Error:
KeyError at /api/fcm/
'active'

**Comment by AlexisCaffa** [comment]
It could be closed when the new version is released.

**Comment by xtrinch** [comment]
Released in 0.3.0
