### ISSUE TITLE
Please make the AppConfig's verbose_name configurable

### ISSUE THREAD

**Issue by ataylor32** [xtrinch/fcm-django#95]
This is the way the class appears at the time of this writing:

```python
class FcmDjangoConfig(AppConfig):
    name = 'fcm_django'
    verbose_name = _('FCM Django')
```

Are you willing to make `verbose_name` configurable? I'm working on a project where the site owner would prefer to have it named "Firebase Cloud Messaging" instead.

**Comment by xtrinch** [comment]
Ofcourse. Care to submit a pull request?
