### ISSUE TITLE
Why pin version of pyfcm?

### ISSUE THREAD

**Issue by zt-initech** [xtrinch/fcm-django#98]
If pyfcm needs to be at least 1.4.5, make it `>= 1.4.5`, but I now want to install the latest which is 1.4.7 and pip complains that it's incompatible.

**Comment by xtrinch** [comment]
Well in the past some newer versions were not backwards compatible.

**Comment by artemistomaras** [comment]
@xtrinch thanks for this package.

It might be best to either make it ``>= 1.4.5`` or issue a new release with the latest ``pyfcm`` version

**Comment by xtrinch** [comment]
New release sounds better :)
