### ISSUE TITLE
The active field is set to false when testing

### ISSUE THREAD

**Issue by Flexonze** [xtrinch/fcm-django#99]
Hi,

I was creating some tests for a view which, among other things, is sending notifications to users when I realized the view was making ALOT of queries. After investigating a bit, I've realized that for each device, a query is made to set the `active` field to `False`. Heres a concrete example:

I have this factory:
```
class FCMDeviceFactory(factory.django.DjangoModelFactory):
    name = factory.Faker('name')
    active = True
    date_created = timezone.now()
    registration_id = factory.Faker('pystr', min_chars=20, max_chars=40)
    type = "android"
    user = factory.SubFactory(UserFactory)

    class Meta:
        model = FCMDevice
```
And here's a simple test: 
```
def test_sending_messages_queries(self):
    user = factories.UserFactory()
    factories.FCMDeviceFactory.create_batch(3, user=user)

    with self.assertNumQueries(2):
        devices = FCMDevice.objects.filter(user=user)
        devices.send_message(
            title='this is a title',
            body='this is a body',
            tag='tag',
        )
```
Here's the captured queries:
```
Captured queries were:
1. SELECT "fcm_django_fcmdevice"."id", "fcm_django_fcmdevice"."name", "fcm_django_fcmdevice"."active", "fcm_django_fcmdevice"."user_id", "fcm_django_fcmdevice"."date_created", "fcm_django_fcmdevice"."device_id", "fcm_django_fcmdevice"."registration_id", "fcm_django_fcmdevice"."type" FROM "fcm_django_fcmdevice" WHERE "fcm_django_fcmdevice"."user_id" = 4

2. SELECT "fcm_django_fcmdevice"."registration_id" FROM "fcm_django_fcmdevice" WHERE ("fcm_django_fcmdevice"."user_id" = 4 AND "fcm_django_fcmdevice"."active" = true)

3. UPDATE "fcm_django_fcmdevice" SET "active" = false WHERE ("fcm_django_fcmdevice"."user_id" = 4 AND "fcm_django_fcmdevice"."registration_id" = 'isRAjabkdUREnbAOYPpcOmzMDfZDpJoDQznVFSR')

4. UPDATE "fcm_django_fcmdevice" SET "active" = false WHERE ("fcm_django_fcmdevice"."user_id" = 4 AND "fcm_django_fcmdevice"."registration_id" = 'LeAAJaqsKaeTUlzlINwHZXI')

5. UPDATE "fcm_django_fcmdevice" SET "active" = false WHERE ("fcm_django_fcmdevice"."user_id" = 4 AND "fcm_django_fcmdevice"."registration_id" = 'IiNMVXdMznrWdpyXyjGChsmp')
```
As you see, it's executing a query for each device (in this case 3) to set the `active` field to false. Is there a reason why it does that?

**Comment by xtrinch** [comment]
It's because you're not getting a positive response from fcm server, so they're deactivated

**Comment by Flexonze** [comment]
Oh, okay. Is there a way to avoid deactivating the device in that case? I don't think that this is something I want.

**Comment by xtrinch** [comment]
Hmm well not as of now. Feel free to submit a pull request to parametrize that, and I will include it in the next release.

**Comment by ernesto-handy** [comment]
Is there a way to catch if there was a negative responde from fcm service and know why it was caused?

**Comment by Almaral-Engineering** [comment]
@Flexonze you can see why is being set to false like this:

result = devices.send_message(data=data)
print(str(result))

And result is going to tell you why. In my case I got this:
[{'multicast_id': 7253873515195786212, 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results': [{'error': 'MessageTooBig'}]}]
